### ISSUE TITLE
Disable highlight.js 

### ISSUE THREAD

**Issue by sebastian-cb** [Zenithar/hugo-theme-crisp#1]
Hi,

Could you please advise how to remove a code related to 'highlight.js'

The auto language detection is not working properly and it adds unnecessary highlights.

It looks like related code is located in this file but I'm not sure which part I need to remove it:

```
https://github.com/Zenithar/hugo-theme-crisp/blob/master/layouts/partials/footer.html
```

Regards
Sebastian

**Comment by Zenithar** [comment]
Hello,

Just remove the #L13, and #L22 from the footer.html, and it will do the job ^^

Regards,

**Comment by sebastian-cb** [comment]
Perfect, thanks.
