### ISSUE TITLE
Issue when generating theme site

### ISSUE THREAD

**Issue by spf13** [Zenithar/hugo-theme-crisp#5]
Building site for theme crisp using config config-crisp.toml
ERROR: 2016/01/06 17:28:27 template.go:120: template: theme/partials/related.html:5:23: executing "theme/partials/related.html" at <.RelatedPages>: RelatedPages is not a field of struct type *hugolib.Page in theme/partials/related.html
ERROR: 2016/01/06 17:28:27 template.go:120: template: theme/partials/related.html:5:23: executing "theme/partials/related.html" at <.RelatedPages>: RelatedPages is not a field of struct type *hugolib.Page in theme/partials/related.html
ERROR: 2016/01/06 17:28:27 template.go:120: template: theme/partials/related.html:5:23: executing "theme/partials/related.html" at <.RelatedPages>: RelatedPages is not a field of struct type *hugolib.Page in theme/partials/related.html
ERROR: 2016/01/06 17:28:27 template.go:120: template: theme/partials/related.html:5:23: executing "theme/partials/related.html" at <.RelatedPages>: RelatedPages is not a field of struct type *hugolib.Page in theme/partials/related.html
ERROR: 2016/01/06 17:28:27 template.go:120: template: theme/partials/related.html:5:23: executing "theme/partials/related.html" at <.RelatedPages>: RelatedPages is not a field of struct type *hugolib.Page in theme/partials/related.html

**Comment by Zenithar** [comment]
Ok it's a feature I have added to Hugo. Let me remove those tags.
