### ISSUE TITLE
Errors on site without expected parameters set

### ISSUE THREAD

**Issue by paskal** [Zenithar/hugo-theme-crisp#9]
Hello!

$subj, when trying to run this theme against my [blog](https://github.com/paskal/terrty/tree/master/blog) source I get following:

```
Building sites … ERROR 2018/03/20 13:38:05 in .Render: Failed to execute template "theme/_default/list.html": template: theme/_default/list.html:13:33: executing "theme/_default/list.html" at <.Paginate>: error calling Paginate: Paginators not supported for pages of type "page" ("Lust for life")
ERROR 2018/03/20 13:38:05 in .Render: Failed to execute template "theme/_default/list.html": template: theme/_default/list.html:13:33: executing "theme/_default/list.html" at <.Paginate>: error calling Paginate: Paginators not supported for pages of type "page" ("How to build code remotely in Visual Studio Code")
```
~The site won't render at all.~ Won't true, I've rechecked - it renders, pagination is working but posts preview isn't working - single post and 4 pages of my blog, and posts list by tag is available.

Also screenshots on the end of README aren't working anymore:
![image](https://user-images.githubusercontent.com/712534/37657975-769456a8-2c5d-11e8-9270-3a5a0d368f33.png)

**Comment by farmergreg** [comment]
i have the same problem.
